#!/usr/bin/env node
/**
 * Kern Duel content generator (Epic 03, plan §2.4 step 3).
 * Merges words.json (authoring source) + measured-output.json (real font
 * kerning data from the dev measurement route) into a deterministic,
 * re-runnable SQL migration. Round ids are uuid_generate_v5(namespace,
 * "word:fontKey") so re-running after a content edit UPDATES that word's
 * row instead of duplicating it (plan K12).
 *
 * Usage: node scripts/kern-duel/generate-seed.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');
const NAMESPACE_UUID = '6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11';
const MIN_OFFSET_PX = -60;
const MAX_OFFSET_PX = 60;

function fail(message) {
  console.error(`[kern-duel:generate-seed] ${message}`);
  process.exit(1);
}

function sqlJsonLiteral(obj) {
  return `'${JSON.stringify(obj).replace(/'/g, "''")}'::jsonb`;
}

const words = JSON.parse(readFileSync(join(REPO_ROOT, 'src/games/kern-duel/content/words.json'), 'utf8'));
const measured = JSON.parse(readFileSync(join(__dirname, 'measured-output.json'), 'utf8'));

// K10: reject duplicate (word, fontKey) entries in the authoring source.
const seen = new Set();
for (const entry of words) {
  const key = `${entry.word}:${entry.fontKey}`;
  if (seen.has(key)) fail(`duplicate content entry "${entry.word}" / "${entry.fontKey}" in words.json`);
  seen.add(key);
}

const measuredByKey = new Map(measured.map((m) => [`${m.word}:${m.fontKey}`, m]));

const rows = words.map((entry) => {
  const key = `${entry.word}:${entry.fontKey}`;
  const m = measuredByKey.get(key);
  // K11: fail loudly rather than emit null/undefined offsets into SQL.
  if (!m) fail(`no measurement found for "${entry.word}" / "${entry.fontKey}" — run the /dev/kern-duel-measure route and update measured-output.json`);

  const letters = m.letters;
  // K3: zero movable letters is a meaningless round; reject at generation time.
  if (letters.length < 3) fail(`word "${entry.word}" has fewer than 3 letters (min 3 required, plan K3)`);

  const lockedIndices = [0, letters.length - 1];
  const offsets =
    entry.overrideOffsets ??
    letters.map((_, i) => +(m.kernedPositions[i] - m.naturalPositions[i]).toFixed(3));

  const payload = {
    word: entry.word,
    letters,
    fontKey: entry.fontKey,
    naturalPositions: m.naturalPositions,
    lockedIndices,
    minOffsetPx: MIN_OFFSET_PX,
    maxOffsetPx: MAX_OFFSET_PX,
    difficulty: entry.difficulty,
  };
  const truth = { offsets, lockedIndices };

  return `insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('${NAMESPACE_UUID}'::uuid, '${key.replace(/'/g, "''")}'),
  (select id from public.games where slug = 'kern-duel'),
  ${sqlJsonLiteral(payload)},
  ${sqlJsonLiteral(truth)},
  ${entry.difficulty},
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;`;
});

const sql = `-- ============================================================================
-- Kern Duel content seed (Epic 03)
-- Source of truth: docs/plan/epic-03-implementation-plan.md §2.4
--
-- GENERATED by scripts/kern-duel/generate-seed.mjs — do not hand-edit the
-- insert block below; edit src/games/kern-duel/content/words.json and
-- regenerate instead (see src/games/kern-duel/README.md).
--
-- Paste-ready for the Supabase SQL Editor. Additive: enables uuid-ossp and
-- inserts/updates rows in the already-existing \`rounds\` table (schema from
-- migration 00000000000001). Safe to re-run after content changes — round
-- ids are deterministic (uuid_generate_v5), so re-running this file UPDATES
-- existing words in place rather than duplicating them (plan K12).
-- ============================================================================

create extension if not exists "uuid-ossp";

-- Ensure the kern-duel game is active now that real content exists.
update public.games set is_active = true where slug = 'kern-duel';

${rows.join('\n\n')}
`;

const outPath = join(REPO_ROOT, 'supabase/migrations/00000000000002_kern_duel_seed.sql');
writeFileSync(outPath, sql, 'utf8');
console.log(`[kern-duel:generate-seed] wrote ${rows.length} rounds to ${outPath}`);
