-- ============================================================================
-- Kern Duel content seed (Epic 03)
-- Source of truth: docs/plan/epic-03-implementation-plan.md §2.4
--
-- GENERATED by scripts/kern-duel/generate-seed.mjs — do not hand-edit the
-- insert block below; edit src/games/kern-duel/content/words.json and
-- regenerate instead (see src/games/kern-duel/README.md).
--
-- Paste-ready for the Supabase SQL Editor. Additive: enables uuid-ossp and
-- inserts/updates rows in the already-existing `rounds` table (schema from
-- migration 00000000000001). Safe to re-run after content changes — round
-- ids are deterministic (uuid_generate_v5), so re-running this file UPDATES
-- existing words in place rather than duplicating them (plan K12).
-- ============================================================================

create extension if not exists "uuid-ossp";

-- Ensure the kern-duel game is active now that real content exists.
update public.games set is_active = true where slug = 'kern-duel';

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Fly:poppins'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Fly","letters":["F","l","y"],"fontKey":"poppins","naturalPositions":[0,35.59375,53.375],"lockedIndices":[0,2],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":1}'::jsonb,
  '{"offsets":[0,0,0],"lockedIndices":[0,2]}'::jsonb,
  1,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Wavy:poppins'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Wavy","letters":["W","a","v","y"],"fontKey":"poppins","naturalPositions":[0,60.40625,88.8125,120.8125],"lockedIndices":[0,3],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":1}'::jsonb,
  '{"offsets":[0,-5.125,-5.125,-5.125],"lockedIndices":[0,3]}'::jsonb,
  1,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Tower:poppins'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Tower","letters":["T","o","w","e","r"],"fontKey":"poppins","naturalPositions":[0,39.09375,71.09375,117.3125,145.71875],"lockedIndices":[0,4],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":2}'::jsonb,
  '{"offsets":[0,-4.469,-4.469,-4.469,-4.469],"lockedIndices":[0,4]}'::jsonb,
  2,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Avatar:poppins'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Avatar","letters":["A","v","a","t","a","r"],"fontKey":"poppins","naturalPositions":[0,46.21875,78.21875,106.625,124.40625,152.8125],"lockedIndices":[0,5],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":2}'::jsonb,
  '{"offsets":[0,-4.75,-4.75,-4.75,-4.75,-4.75],"lockedIndices":[0,5]}'::jsonb,
  2,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Toy:playfair-display'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Toy","letters":["T","o","y"],"fontKey":"playfair-display","naturalPositions":[0,39.09375,71.09375],"lockedIndices":[0,2],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":1}'::jsonb,
  '{"offsets":[0,-4.469,-4.469],"lockedIndices":[0,2]}'::jsonb,
  1,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Type:playfair-display'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Type","letters":["T","y","p","e"],"fontKey":"playfair-display","naturalPositions":[0,39.09375,71.09375,103.09375],"lockedIndices":[0,3],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":1}'::jsonb,
  '{"offsets":[0,-4.469,-4.469,-4.469],"lockedIndices":[0,3]}'::jsonb,
  1,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Watch:playfair-display'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Watch","letters":["W","a","t","c","h"],"fontKey":"playfair-display","naturalPositions":[0,60.40625,88.8125,106.59375,135],"lockedIndices":[0,4],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":2}'::jsonb,
  '{"offsets":[0,-5.125,-5.125,-5.125,-5.125],"lockedIndices":[0,4]}'::jsonb,
  2,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Waterfall:playfair-display'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Waterfall","letters":["W","a","t","e","r","f","a","l","l"],"fontKey":"playfair-display","naturalPositions":[0,60.40625,88.8125,106.59375,135,156.3125,177.625,206.03125,223.8125],"lockedIndices":[0,8],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":3}'::jsonb,
  '{"offsets":[0,-5.125,-5.125,-5.125,-5.125,-5.125,-5.125,-5.125,-5.125],"lockedIndices":[0,8]}'::jsonb,
  3,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Away:inter'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Away","letters":["A","w","a","y"],"fontKey":"inter","naturalPositions":[0,44.15625,90.375,118.78125],"lockedIndices":[0,3],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":1}'::jsonb,
  '{"offsets":[0,0,0,0],"lockedIndices":[0,3]}'::jsonb,
  1,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Float:inter'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Float","letters":["F","l","o","a","t"],"fontKey":"inter","naturalPositions":[0,35.59375,53.375,85.375,113.78125],"lockedIndices":[0,4],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":2}'::jsonb,
  '{"offsets":[0,0,0,0,0],"lockedIndices":[0,4]}'::jsonb,
  2,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Toast:inter'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Toast","letters":["T","o","a","s","t"],"fontKey":"inter","naturalPositions":[0,39.09375,71.09375,99.5,124.40625],"lockedIndices":[0,4],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":2}'::jsonb,
  '{"offsets":[0,-4.469,-4.469,-4.469,-4.469],"lockedIndices":[0,4]}'::jsonb,
  2,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Typewriter:inter'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Typewriter","letters":["T","y","p","e","w","r","i","t","e","r"],"fontKey":"inter","naturalPositions":[0,39.09375,71.09375,103.09375,131.5,177.71875,199.03125,216.8125,234.59375,263],"lockedIndices":[0,9],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":3}'::jsonb,
  '{"offsets":[0,-4.469,-4.469,-4.469,-4.469,-4.469,-4.469,-4.469,-4.469,-4.469],"lockedIndices":[0,9]}'::jsonb,
  3,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Yacht:merriweather'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Yacht","letters":["Y","a","c","h","t"],"fontKey":"merriweather","naturalPositions":[0,46.21875,74.625,103.03125,135.03125],"lockedIndices":[0,4],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":2}'::jsonb,
  '{"offsets":[0,-6.406,-6.406,-6.406,-6.406],"lockedIndices":[0,4]}'::jsonb,
  2,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Tally:merriweather'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Tally","letters":["T","a","l","l","y"],"fontKey":"merriweather","naturalPositions":[0,39.09375,67.5,85.28125,103.0625],"lockedIndices":[0,4],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":2}'::jsonb,
  '{"offsets":[0,-4.469,-4.469,-4.469,-4.469],"lockedIndices":[0,4]}'::jsonb,
  2,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Wafer:merriweather'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Wafer","letters":["W","a","f","e","r"],"fontKey":"merriweather","naturalPositions":[0,60.40625,88.8125,110.125,138.53125],"lockedIndices":[0,4],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":2}'::jsonb,
  '{"offsets":[0,-5.125,-5.125,-5.125,-5.125],"lockedIndices":[0,4]}'::jsonb,
  2,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;

insert into public.rounds (id, game_id, payload, truth, difficulty, is_active)
values (
  uuid_generate_v5('6a1b1c2e-6b7a-4a1d-8f2e-1a9c9b6d0e11'::uuid, 'Toffee:merriweather'),
  (select id from public.games where slug = 'kern-duel'),
  '{"word":"Toffee","letters":["T","o","f","f","e","e"],"fontKey":"merriweather","naturalPositions":[0,39.09375,71.09375,92.40625,113.71875,142.125],"lockedIndices":[0,5],"minOffsetPx":-60,"maxOffsetPx":60,"difficulty":2}'::jsonb,
  '{"offsets":[0,-4.469,-4.469,-5.625,-5.625,-5.625],"lockedIndices":[0,5]}'::jsonb,
  2,
  true
)
on conflict (id) do update set
  payload = excluded.payload,
  truth = excluded.truth,
  difficulty = excluded.difficulty,
  is_active = true;
